// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registrering.Data;

namespace Registrering.Migrations
{
    [DbContext(typeof(AttendeeDbContext))]
    [Migration("20200216081658_motmig")]
    partial class motmig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Registrering.Models.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Accomodation")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SpecialDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("Registrering.Models.Mote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Closed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Committee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommitteeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactGP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Directions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F36")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastChanged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocBorough")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.Property<string>("WheelChr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Zip")
                        .HasColumnType("float");

                    b.Property<string>("latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longitude")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Moter");
                });
#pragma warning restore 612, 618
        }
    }
}
